import {StyleSheet} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import {moderateScale} from 'react-native-size-matters';
import {AppColor} from '../AppUtil';
import {fonts} from '../../components/utilities/images';
import {Platform} from 'react-native';

export const styles = StyleSheet.create({
  image1: {
    position: 'absolute',
    left: moderateScale(275),
  },
  main: {
    marginTop: Platform.OS == 'ios' ? 50 : 0,
    flex: 1,
    backgroundColor: 'white',
  },
  color: {
    backgroundColor: AppColor.white,
    height: 2000,
  },
  arrow: {
    left: moderateScale(30),
    marginTop: moderateScale(65),
    color: 'red',
  },
  circle2: {
    position: 'absolute',
    top: moderateScale(90),
    left: moderateScale(280),
  },
  arrow1: {
    position: 'absolute',
    left: moderateScale(260),
    top: moderateScale(105),
  },
  logo: {
    top: moderateScale(99),
    left: moderateScale(51),
    position: 'absolute',
  },
  hello: {
    top: moderateScale(150),
    left: moderateScale(35),
    fontSize: RFValue(30),
    lineHeight: 35,
    fontFamily: fonts.bold,
    color: AppColor.black,
  },
  state: {
    top: moderateScale(187),
    left: moderateScale(35),
    fontWeight: '400',
    fontSize: RFValue(16),
    position: 'absolute',
    color: AppColor.content,
    fontFamily: fonts.regular,
  },
  user: {
    top: moderateScale(232),
    left: moderateScale(20),
    fontWeight: '400',
    fontSize: RFValue(12),
    position: 'absolute',
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
  },
  name: {
    top: moderateScale(255),
    left: moderateScale(20),
    position: 'absolute',
    fontWeight: '400',
    fontSize: RFValue(12),
    lineHeight: 14,
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
    width: 150,
  },
  childView: {
    position: 'absolute',
    width: moderateScale(313),
    top: moderateScale(273),
    left: moderateScale(20),
    borderBottomWidth: 0.58,
    borderColor: AppColor.borderColor,
  },
  password: {
    top: moderateScale(275),
    left: moderateScale(20),
    fontWeight: '400',
    fontSize: RFValue(12),
    lineHeight: 14,
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
  },
  childView1: {
    width: moderateScale(313),
    top: moderateScale(280),
    left: moderateScale(20),
    borderBottomWidth: 0.58,
    borderColor: AppColor.borderColor,
  },
  rectangle: {
    top: moderateScale(310),
    left: moderateScale(20),
    borderRadius: 1,
    position: 'absolute',
    borderColor: AppColor.greyContent,
  },
  checkBox: {
    height: moderateScale(22),
    width: moderateScale(22),
    borderRadius: 5,
  },
  remember: {
    top: moderateScale(315),
    left: moderateScale(55),
    fontWeight: '400',
    fontSize: RFValue(12),
    // lineHeight: 12,
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
  },
  forgot: {
    top: moderateScale(295),
    left: moderateScale(236),
    fontWeight: '400',
    fontSize: RFValue(12),
    // lineHeight: 12,
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
    height: 45,
  },
  button: {
    width: moderateScale(320),
    height: moderateScale(50),
    top: moderateScale(431),
    left: moderateScale(20),
    borderRadius: 10,
    position: 'absolute',
    backgroundColor: AppColor.purple,
  },
  login: {
    fontSize: RFValue(15),
    color: AppColor.white,
    textAlign: 'center',
    top: moderateScale(15),
    fontFamily: fonts.semiBold,
  },
  account: {
    top: moderateScale(367),
    right: moderateScale(40),
    fontWeight: '400',
    fontSize: RFValue(13),
    lineHeight: 14,
    color: AppColor.greyContent,
    fontFamily: fonts.regular,
  },
  regularTxt: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: moderateScale(40),
  },
  sign: {
    top: moderateScale(365),
    right: moderateScale(-13),
    fontWeight: '400',
    fontSize: RFValue(12),
    lineHeight: 14,
    position: 'absolute',
    color: AppColor.colorContent,
    fontFamily: fonts.regular,
  },
  errorMessage: {
    top: moderateScale(280),
    marginLeft: moderateScale(50),
    position: 'absolute',
    color: AppColor.red,
  },
  errorMessage1: {
    top: moderateScale(335),
    marginLeft: moderateScale(50),
    position: 'absolute',
    color: AppColor.red,
  },
});
